# Generated by Django 4.1.7 on 2023-06-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vedassist", "0002_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_image",
            field=models.ImageField(upload_to="medicine"),
        ),
    ]
