# Generated by Django 4.1.7 on 2023-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vedassist", "0003_alter_medicine_medicine_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="medicine_price",
            field=models.FloatField(default=10.0),
        ),
    ]
